### ISSUE TITLE
app not working with 18

### ISSUE THREAD

**Issue by wiswedel** [rullzer/sharelisting#89]
tested on NC 18.0.0 and 18.0.1 with app v0.1.1 and v0.2.0

cli throws following error:

```
sudo -u www-data php occ sharing:list

An unhandled exception has been thrown:
ParseError: syntax error, unexpected 'fn' (T_FN), expecting identifier (T_STRING) in /var/www/nc18.0.0/apps/sharelisting/vendor/nikic/iter/src/iter.fn.php:3
Stack trace:
#0 /var/www/nc18.0.0/apps/sharelisting/vendor/composer/autoload_real.php(57): require()
#1 /var/www/nc18.0.0/apps/sharelisting/vendor/composer/autoload_real.php(47): composerRequiredba70a5c807966a37061f0e6b056afa8()
#2 /var/www/nc18.0.0/apps/sharelisting/vendor/autoload.php(7): ComposerAutoloaderInitdba70a5c807966a37061f0e6b056afa8::getLoader()
#3 /var/www/nc18.0.0/apps/sharelisting/lib/AppInfo/Application.php(38): require_once('/var/www/nc18.0...')
#4 /var/www/nc18.0.0/lib/private/ServerContainer.php(107): OCA\ShareListing\AppInfo\Application->__construct()
#5 /var/www/nc18.0.0/lib/private/ServerContainer.php(133): OC\ServerContainer->getAppContainer()
#6 /var/www/nc18.0.0/lib/private/Console/Application.php(220): OC\ServerContainer->query()
#7 /var/www/nc18.0.0/lib/private/Console/Application.php(135): OC\Console\Application->loadCommandsFromInfoXml()
#8 /var/www/nc18.0.0/console.php(98): OC\Console\Application->loadCommands()
#9 /var/www/nc18.0.0/occ(11): require_once('/var/www/nc18.0...')
```

Web UI shows nothing where "Shared subitems" was supposed to be (sidebar).

**Comment by rullzer** [comment]
Works just fine here. What php version are you on?

**Comment by wiswedel** [comment]
7.4.3

**Comment by wiswedel** [comment]
```
[PHP Modules]
apc
apcu
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
ldap
libsmbclient
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
```

**Comment by rullzer** [comment]
Let me push a new version to see if that helps for you. I don't see related fixes. but so be it.

**Comment by rullzer** [comment]
Please try 0.3.0 https://apps.nextcloud.com/apps/sharelisting

**Comment by wiswedel** [comment]
Yayy! That does the job again. Thanks for the quick fix, @rullzer ☕
